apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql

        image: mysql:8.0

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: RootPass2024

        - name: MYSQL_DATABASE
          value: campusstay

        - name: MYSQL_USER
          value: campusstay_user

        - name: MYSQL_PASSWORD
          value: CampusStay2024

        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage

      volumes:
      - name: mysql-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  selector:
    app: mysql

  ports:
    - port: 3306
      targetPort: 3306
