apiVersion: v1
kind: Service

metadata:
  name: campusstay-service

spec:
  type: NodePort

  selector:
    app: campusstay-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
